name: Build LaTeX and Notify Parent
on:
  push:
    branches:
      - main
    paths:
      - "*"
      - "images/*"
  workflow_dispatch:
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: BSc_group_k
          path: main.pdf
      - run: "mkdir -p build"
      - run: "mv main.pdf build/BSc_group_k.pdf"
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add build/BSc_group_k.pdf
          git commit -m "Build PDF"
          git push

  notify:
    name: 'Submodule Notify Parent'
    needs: build_latex
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Github REST API Call
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
        PARENT_REPO: git-gurus-itu-devops/itu-minitwit
        PARENT_BRANCH: main
        WORKFLOW_ID: 97571674
      run: |
        curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
        